# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c49309303853e6f9734c240eb15dd3f"
name = "test-polaris-remix"
handle = "test-polaris-remix"
application_url = "https://queen-majority-rural-exemption.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xuanzung0505.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://queen-majority-rural-exemption.trycloudflare.com/auth/callback",
  "https://queen-majority-rural-exemption.trycloudflare.com/auth/shopify/callback",
  "https://queen-majority-rural-exemption.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
